version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER=%{POSTGRES_USER}
    #   - POSTGRES_PASSWORD=%{POSTGRES_PASSWORD}
    #   - POSTGRES_DB=%{POSTGRES_NAME}
    # ports:
    #   - "6543:5432"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 